version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
